name: Upload to App Center

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build APK
        run: ./gradlew :app:assembleDebug

      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1.3.4
        with:
          appName: 'Tristigra/Webhook'
          token: ${{ secrets.APPCENTER_TOKEN }}
          group: 'Testers'
          file: app/build/outputs/apk/debug/app-debug.apk
          releaseNotes: 'Nieuwe build via GitHub 🔥'
